config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  get 'easybreezys/home'
  get 'easybreezys/aboutUs'
  get 'easybreezys/ourWork'
  root 'easybreezys#home'

  get 'typework/landing_page'
  get 'typework/diploma'
  get 'typework/exchange_rate'
  get 'typework/problem_solving'
  get 'typework/programms'
  get 'typework/shop'
  get 'typework/site_card'
  get 'typework/text_translation'


  resources :users, shallow: true do
    resources :requests
  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/request.rb
class Request < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  has_many :requests

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception



end

app/controllers/easybreezys_controller.rb
class EasybreezysController < ApplicationController
  def home

  end

  def aboutUs

  end

  def ourWork

  end
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController

  before_action :set_request, only: [:show, :edit, :update, :destroy]
  before_action :set_user, only: [:index, :create, :new]
  before_filter :authenticate_user!

  def index
    @requests = @user.requests
  end

  def show
    @user = current_user
  end

  def new
    @request = @user.requests.new
  end

  def edit
    @user = current_user
  end

  def create
    @request = @user.requests.new(request_params)
    @request.status = "0"
    @request.email = current_user.email


    UserMailer.signup_conf(@request).deliver


    respond_to do |format|
      if @request.save
        format.html { redirect_to @request, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @request }
      else
        format.html { render :new }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @request, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @request }
      else
        format.html { render :edit }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @request.destroy
    respond_to do |format|
      format.html { redirect_to user_requests_path(current_user), notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  private

    def set_request
      @request = Request.find(params[:id])
    end

    def set_user
      @user = User.find(params[:user_id])
    end

    def request_params
      params.require(:request).permit(:email, :type_request, :body, :time_request, :price, :phone_user, :status, :user_id)
    end

end

app/controllers/typework_controller.rb
class TypeworkController < ApplicationController

  def landing_page
  end
  def site_card
  end
  def shop
  end
  def programms
  end
  def text_translation
  end
  def problem_solving
  end
  def diploma
  end
  def exchange_rate
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/easybreezys_helper.rb
module EasybreezysHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/typework_helper.rb
module TypeworkHelper
end

app/views/easybreezys/aboutUs.html.erb
<div class="jumbotron">
 <center> <h1>Easy Breezy</h1></center>
  <div class="row">
    <div class="col-xs-6">
      <%= image_tag("profit.jpg", alt: "logo", class: "img-rounded img-responsive") %>
    </div>
    <div class="col-xs-6">
    <p>
    </p>
    

      <p><font face:"OpenSansBold">  
       Мы компания, которая занимается разработкой Вэб-сайтов и программ на разных языках программирования. Также помогаем студентам в написании дипломных и курсовых работ. Решаем различные задачи по математике (мат. анализ, дифференциальные уравнения, линейная алгебра, тер вер, мат стат).</font></p>
    </div>
  </div>
  <p></p>
  <p> 
Название компании Easy-Breezy вытекает из того, что мы с радостью беремся за работу и с легкостью ее выполняем. Чему соответствует наш девиз - «Решаем сложные задачи просто и быстро!» </p>
<p>Большинство сотрудников компании являются специалистами в области информационных технологий, т.к. закончили Казанский Федеральный Университет по соответствующим направлениям. </p>
<p>Мы молодая, быстроразвивающаяся компания, которая готова взяться за сложные и неординарные задачи. Всегда стремимся предложить оригинальный способ решения. Являемся участниками и победителями различных конкурсов по программированию и написанию приложений. </p>
<p>В будущем планируем углубиться в разработку Android и IOS приложений. Также будем предлагать свои услуги в SEO, SEM и SMM продвижении. </p>
<p>Обращайтесь к нам и вы будете довольный выполненной работой!</p>
  
</div>

app/views/easybreezys/home.html.erb
  <div class="jumbotron">
    <h2>Разработка web-сайтов, написание программ, решение задач по математике!</h2>
    <p><span class="glyphicon glyphicon-triangle-right" aria-hidden="true"></span> "Решаем сложные задачи просто и быстро!"</p>
  </div>


  <div class="contrainer-fluid">
    <div class="row">
      <div class="col-xs-6">
       <h3> <ul class="list-group">
         <li class="list-group-item"><%= link_to content_tag(:span," ", class: "glyphicon glyphicon-ok") + ' Landing page', typework_landing_page_path %></li>
         <li class="list-group-item"><%= link_to content_tag(:span," ", class: "glyphicon glyphicon-ok") + ' Сайт визитка', typework_site_card_path %></li>
         <li class="list-group-item"><%= link_to content_tag(:span," ", class: "glyphicon glyphicon-ok") + ' Интернет магазин', typework_shop_path %></li>
         <li class="list-group-item"><%= link_to content_tag(:span," ", class: "glyphicon glyphicon-ok") + ' Программы на с++, с#, java, python, ruby, ror, php', typework_programms_path %></li>
      </ul></h3>
      </div>
      <div class="col-xs-6">
      <h3>  <ul class="list-group">
          <li class="list-group-item"><%= link_to content_tag(:span," ", class: "glyphicon glyphicon-ok") + ' Дипломные работы', typework_diploma_path %></li>
          <li class="list-group-item"><%= link_to content_tag(:span," ", class: "glyphicon glyphicon-ok") + ' Курсовая работы', typework_exchange_rate_path %></li>
          <li class="list-group-item"><%= link_to content_tag(:span," ", class: "glyphicon glyphicon-ok") + ' Переводы на или с английского', typework_text_translation_path %></li>
          <li class="list-group-item"><%= link_to content_tag(:span," ", class: "glyphicon glyphicon-ok") + ' Решение задач по математике (мат анализ, дифуры, линейная алгебра, тер вер, мат стат.)', typework_problem_solving_path %></li>
      </ul></h3>
      </div>
    </div>
  </div>

app/views/easybreezys/ourWork.html.erb
<div class="row row-margin-bottom">
  <div class="col-xs-12 col-lg-6 col-md-5 no-padding lib-item" data-category="view">
    <div class="lib-panel asd">
      <div class="row box-shadow">
        <a href="https://mysuperpuperblog.herokuapp.com/">
        <div class="col-xs-12 col-lg-6 col-md-6 img-site">
          <%=  image_tag("blog_gal.png", alt: "ourWork", class: "img-thumbnail lib-img-show") %>
        </div>
        </a>
        <div class="col-xs-12 col-lg-6 col-md-6">
          <div class="lib-row lib-header">
            Example library
            <div class="lib-header-seperator"></div>
          </div>
          <div class="lib-row lib-desc">
            Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="col-xs-1 col-md-2"></div>
  <div class="col-xs-12 col-lg-6 col-md-5 no-padding lib-item" data-category="ui">
    <div class="lib-panel">
      <div class="row box-shadow">
        <div class="col-xs-12 col-lg-6 col-md-6 img-site">
          <%=  image_tag("blog_gal.png", alt: "ourWork", class: "img-thumbnail lib-img-show") %>
        </div>
        <div class="col-xs-12 col-lg-6 col-md-6">
          <div class="lib-row lib-header">
            Example library
            <div class="lib-header-seperator"></div>
          </div>
          <div class="lib-row lib-desc">
            Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="col-xs-12 col-lg-6 col-md-5 no-padding lib-item" data-category="view">
    <div class="lib-panel">
      <div class="row box-shadow">
        <div class="col-xs-12 col-lg-6 col-md-6 img-site">
          <%=  image_tag("blog_gal.png", alt: "ourWork", class: "img-thumbnail lib-img-show") %>
        </div>
        <div class="col-xs-12 col-lg-6 col-md-6">
          <div class="lib-row lib-header">
            Example library
            <div class="lib-header-seperator"></div>
          </div>
          <div class="lib-row lib-desc">
            Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="col-md-1"></div>
  <div class="col-xs-12 col-lg-6 col-md-5 no-padding lib-item" data-category="ui">
    <div class="lib-panel">
      <div class="row box-shadow">
        <div class="col-xs-12 col-lg-6 col-md-6 img-site">
          <%=  image_tag("blog_gal.png", alt: "ourWork", class: "img-thumbnail lib-img-show") %>
        </div>
        <div class="col-xs-12 col-lg-6 col-md-6">
          <div class="lib-row lib-header">
            Example library
            <div class="lib-header-seperator"></div>
          </div>
          <div class="lib-row lib-desc">
            Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer p-t-1">
  <div class="container">
    <div class="row">
      <div class="col-xs-4">
        <p>© 2016 Easy-Breezy Company </p>
      </div>
      <div class="col-xs-8">
        <ul class="list-unstyled list-inline pull-right">
          <li><span class="glyphicon glyphicon-phone" aria-hidden="true"></span> 89274203049</li>
          <li><span class="glyphicon glyphicon-envelope" aria-hidden="true"></span> alfaalbettasd#fasdf.com</li>
        </ul>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<div class="navbar-wrapper">
  <div class="container-fluid">
    <nav class="navbar navbar-fixed-top navbar-header">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to image_tag("easy.png", alt: "logo", width: "90px"), easybreezys_home_path, class: "navbar-brand" %>
        </div>
        <div id="navbar" class="navbar-collapse collapse pull-centre">

          <ul class="nav navbar-nav pull-right">
            <ul class="nav navbar-nav">
              <li class="active"><%= link_to 'О нас', easybreezys_aboutUs_path, class: "" %></li>
              <li><%= link_to 'Наши работы', easybreezys_ourWork_path %></li>
              <% if user_signed_in? %>
                  <li><%= link_to 'Оставить заявку', new_user_request_path(current_user) %></li>
              <% end %>

            </ul>
            <% if user_signed_in? %>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.email %> <span class="caret"></span></a>
                  <ul class="dropdown-menu">
                    <li><%= link_to 'Редактировать профиль', edit_user_registration_path %></li>
                    <li><%= link_to 'Заказы', user_requests_path(current_user) %></li>
                    <li> <%= link_to 'Выйти', destroy_user_session_path, :method => :delete %></li>
                  </ul>
                </li>

            <% else %>
                <li><%= link_to 'Войти', new_user_session_path %></li>
                <li><%= link_to 'Зарегистрироваться', new_user_registration_path %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EasyBreezy</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <%= render 'layouts/header' %>
      <div class="container body_container">
          <%= yield %>
      </div>

      <%= render 'layouts/footer' %>
  </body>
</html>

app/views/persons/ourWork.html.erb
<div class="row">
  <div class="col-lg-6">
    <a href="#" class="thumbnail">
      <p>Pulpit Rock: A famous tourist attraction in Forsand, Ryfylke, Norway.</p>
      <%= image_tag("blog_gal.png", alt: "ourWork") %>
    </a>
  </div>
  <div class="col-lg-6">
    <a href="moustiers-sainte-marie.jpg" class="thumbnail">
      <p>Moustiers-Sainte-Marie: Considered as one of the "most beautiful villages of France".</p>
      <%= image_tag("blog_gal.png", alt: "ourWork") %>
    </a>
  </div>
  <div class="clearfix"></div>
  <div class="col-md-6">
    <a href="cinqueterre.jpg" class="thumbnail">
      <p>The Cinque Terre: A rugged portion of coast in the Liguria region of Italy.</p>
      <%= image_tag("blog_gal.png", alt: "ourWork") %>
    </a>
  </div>
</div>

app/views/persons/profile.html.erb
  <div class="jumbotron">
    <h1>Добро пожаловать!</h1>
    <p>Bootstrap is the most popular HTML, CSS, and JS framework for developing responsive, mobile-first projects on the web.</p>
  </div>


  <div class="contrainer-fluid">
    <div class="row">
      <div class="col-xs-6">
        <ul class="list-group">
        <li class="list-group-item"><span class="glyphicon glyphicon-ok" aria-hidden="true"></span> landing page</li>
        <li class="list-group-item"><span class="glyphicon glyphicon-ok" aria-hidden="true"></span> Сайт визитка</li>
        <li class="list-group-item"><span class="glyphicon glyphicon-ok" aria-hidden="true"></span> Интернет Магазин</li>
        <li class="list-group-item"><span class="glyphicon glyphicon-ok" aria-hidden="true"></span> Программы на с++, с#, java, python, ruby, ror, php</li>
      </ul>
      </div>
      <div class="col-xs-6">
        <ul class="list-group">
          <li class="list-group-item"><span class="glyphicon glyphicon-ok" aria-hidden="true"></span> Дипломные работы</li>
          <li class="list-group-item"><span class="glyphicon glyphicon-ok" aria-hidden="true"></span> Курсовые работы</li>
          <li class="list-group-item"><span class="glyphicon glyphicon-ok" aria-hidden="true"></span> Переводы на или с английского</li>
          <li class="list-group-item"><span class="glyphicon glyphicon-ok" aria-hidden="true"></span> Решение задач по математике (мат анализ, дифуры, линейная алгебра, тер вер, мат стат.)</li>
      </ul>
      </div>
    </div>
  </div>

app/views/requests/_form.html.erb
<div class="row main">
  <div class="panel-heading">
    <div class="panel-title text-center">
      <h2 class="title">Вход</h2>
      <hr />
    </div>
  </div>
  <div class="main-login main-center">
    <%= form_for ([@request.user, @request]) do |f| %>
        <div class="form-group">
          <%= f.label :Тип_заказа, class: "cols-sm-2 control-label" %><br />
          <div class="cols-sm-10">
            <div class="input-group">
              <span class="input-group-addon"><i class="fa fa-lock fa-lg" aria-hidden="true"></i></span>
              <%= f.select :type_request, options_for_select(["landing page","Сайт визитка","Интернет Магазин","Программы на с++, с#, java, python, ruby, ror, php","Дипломные работы","Курсовые работы","Переводы на или с английского","Решение задач по математике"]), class: "form-control" %>
           </div>
          </div>
        </div>

        <div class="form-group">
          <%= f.label :Описание_заказа, class: "cols-sm-2 control-label" %><br />
          <div class="cols-sm-10">
            <div class="input-group">
              <span class="input-group-addon"><i class="fa fa-lock fa-lg" aria-hidden="true"></i></span>
              <%= f.text_area :body, class: "form-control" %>
            </div>
          </div>
        </div>

        <div class="form-group">
          <%= f.label :Время, class: "cols-sm-2 control-label" %><br />
          <div class="cols-sm-10">
            <div class="input-group">
              <span class="input-group-addon"><i class="fa fa-lock fa-lg" aria-hidden="true"></i></span>
              <%= f.date_field(:time_request,class: "form-control") %>
            </div>
          </div>
        </div>

        <div class="form-group">
          <%= f.label :Цена, class: "cols-sm-2 control-label" %><br />
          <div class="cols-sm-10">
            <div class="input-group">
              <span class="input-group-addon"><i class="fa fa-lock fa-lg" aria-hidden="true"></i></span>
              <%= f.text_field :price, class: "form-control" %>
            </div>
          </div>
        </div>


        <div class="form-group">
          <%= f.label :Телефон, class: "cols-sm-2 control-label" %><br />
          <div class="cols-sm-10">
            <div class="input-group">
              <span class="input-group-addon"><i class="fa fa-lock fa-lg" aria-hidden="true"></i></span>
              <%= f.telephone_field(:phone_user, class: "form-control") %>
            </div>
          </div>
        </div>

        <div class="form-group ">
          <%= f.submit "Сделать заказ", class: "btn btn-primary btn-lg btn-block login-button" %>
        </div>

    <% end %>
  </div>
</div>

app/views/requests/_index.html.erb
<div class="row">

  <% if(@requests.empty?) %>
      <div class="col-sm-3 col-md-3"></div>
      <div class="col-sm-6 col-md-6">
        <div class="well">
          <h2 class="text-muted">Вы еще не оставляли заявок</h2>
         </div>
      </div>
      <div class="col-sm-3 col-md-3"></div>
  <% else %>
  <% @requests.each do |request| %>
  <div class="col-sm-6 col-md-6">
    <div class="well">
      <h2 class="text-muted"><%= request.type_request %></h2>
      <p><span class="label label-default">Status: <%= request.status %></span></p>

      <p><%= request.body %></p>
      <hr>
      <h3><%= request.price  %> | <%= request.time_request%></h3>
      <hr>
      <%= link_to 'Просмотреть', request, class: "btn btn-default btn-sm"  %>
      <%= link_to 'Удалить', request, method: :delete, data: { confirm: 'Вы уверены?' } , class: "btn btn-default btn-sm" %>
    </div>
  </div>
      <% end %>
      <% end %>
</div>

app/views/requests/index.html.erb
<%= render 'index' %>

app/views/requests/new.html.erb
<%= render 'form' %>

app/views/requests/show.html.erb
<div class="row">
  <div class="col-sm-3 col-md-3"></div>
  <div class="col-sm-6 col-md-6">
  <div class="well">
    <h2 class="text-muted"><%= @request.type_request %></h2>
    <p><span class="label label-default">Status: <%= @request.status %></span></p>

    <p><%= @request.body %></p>
    <hr>
    <h3><%= @request.price  %> | <%= @request.time_request%></h3>
    <hr>
    <%= link_to 'Удалить', @request, method: :delete, data: { confirm: 'Вы уверены?' } , class: "btn btn-default btn-sm" %>
  </div>
</div>
  <div class="col-sm-3 col-md-3"></div>
</div>

app/views/typework/diploma.html.erb
sdasd

app/views/typework/exchange_rate.html.erb
dsad

app/views/typework/landing_page.html.erb
asd

app/views/typework/problem_solving.erb
dsad

app/views/typework/programms.html.erb
asdasd

app/views/typework/shop.html.erb
sa

app/views/typework/site_card.html.erb
dasd

app/views/typework/text_translation.html.erb
asdad